server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /api/auth/ {
    proxy_pass http://authservice:3001/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/products/ {
    proxy_pass http://productservice:3003/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/orders/ {
    proxy_pass http://orderservice:3002/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/users/ {
    proxy_pass http://userservice:3004/users/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/chat/ {
    proxy_pass http://chatservice:3005/chat/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}